---
# Arch Linux Hyprland Desktop Setup
# Run with: ansible-playbook setup.yml --ask-become-pass

- name: Setup Arch Linux with Hyprland
  hosts: localhost
  become: false

  pre_tasks:
    - name: Update pacman cache
      become: true
      pacman:
        update_cache: true

    - name: Gather hardware facts
      import_role:
        name: hardware
        tasks_from: detect

  roles:
    - role: base
      tags: [base, packages]

    - role: aur
      tags: [aur, packages]

    - role: zsh
      tags: [zsh, shell]

    - role: hyprland
      tags: [hyprland, desktop]

    - role: nvidia
      when: has_nvidia_gpu | default(false)
      tags: [nvidia, drivers]

    - role: themes
      tags: [themes, appearance]

    - role: dotfiles
      tags: [dotfiles, config]

    - role: services
      tags: [services, systemd]

  post_tasks:
    - name: Display completion message
      debug:
        msg: |
          ============================================
          Hyprland setup complete!

          Hardware detected:
            - GPU: {{ 'NVIDIA' if has_nvidia_gpu else 'AMD/Intel' }}
            - Type: {{ hardware_type | default('desktop') }}

          *** REBOOT NOW: sudo reboot ***

          After reboot:
            1. tuigreet login screen will appear
            2. Press F2 to select session -> choose 'Hyprland'
            3. Enter username and password

          Keybindings (default):
            - SUPER + Enter: Terminal (ghostty)
            - SUPER + Space: App launcher (wofi)
            - SUPER + Q: Close window
            - SUPER + SHIFT + L: Lock screen (hyprlock)
            - SUPER + 1-9: Switch workspace

          Config location: ~/.config/hypr/
          Lock screen: hyprlock (already configured)
          ============================================
